const navbarItems = [
  {
    id: 0,
    title: "home",
    link: String.raw`/`,
  },
  {
    id: 1,
    title: "about me",
    link: String.raw`/about`,
  },
  {
    id: 2,
    title: "contact me",
    link: String.raw`/contact`,
  },
  {
    id: 3,
    title: "projects",
    link: String.raw`/projects`,
  },
  {
    id: 4,
    title: "technical documents",
    link: String.raw`/docs`,
  },
];

const avatarIons = [
  {
    id: "react-orbital-icon",
    src: String.raw`\icons\reactIcon.png`,
    rotateZ: 60,
    rotateY: 80,
    delay: 0,
    shadow: "cyan",
  },
  {
    id: "angular-orbital-icon",
    src: String.raw`icons\angularIcon.png`,
    rotateZ: 60,
    rotateY: 80,
    delay: 0.8,
    shadow: "red",
  },
  {
    id: "flutter-orbital-icon",
    src: String.raw`icons\flutterIcon.png`,
    rotateZ: 60,
    rotateY: 80,
    delay: 1.6,
    shadow: "cyan",
  },
  {
    id: "github-orbital-icon",
    src: String.raw`icons\githubIcon.png`,
    rotateZ: 60,
    rotateY: 80,
    delay: 2.4,
    shadow: "white",
  },
  {
    id: "node-orbital-icon",
    src: String.raw`icons\nodeIcon.png`,
    rotateZ: -60,
    rotateY: 80,
    delay: 0.3,
    shadow: "green",
  },
  {
    id: "fastAPI-orbital-icon",
    src: String.raw`icons\fastAPI.png`,
    rotateZ: -60,
    rotateY: 80,
    delay: 1.1,
    shadow: "cyan",
  },
  {
    id: "docker-orbital-icon",
    src: String.raw`icons\dockerIcon.png`,
    rotateZ: -60,
    rotateY: 80,
    delay: 1.9,
    shadow: "white",
  },
  {
    id: "django-orbital-icon",
    src: String.raw`icons\djangoIcon.png`,
    rotateZ: -60,
    rotateY: 80,
    delay: 2.7,
    shadow: "white",
  },
  {
    id: "html-orbital-icon",
    src: String.raw`icons\htmlIcon.png`,
    rotateZ: 0,
    rotateY: 80,
    delay: 0.6,
    shadow: "orange",
  },
  {
    id: "css-orbital-icon",
    src: String.raw`icons\cssIcon.png`,
    rotateZ: 0,
    rotateY: 80,
    delay: 1.4,
    shadow: "lightblue",
  },
  {
    id: "js-orbital-icon",
    src: String.raw`icons\jsIcon.png`,
    rotateZ: 0,
    rotateY: 80,
    delay: 2.2,
    shadow: "yellow",
  },
  {
    id: "python-orbital-icon",
    src: String.raw`icons\pythonIcon.png`,
    rotateZ: 0,
    rotateY: 80,
    delay: 3,
    shadow: "blue",
  },
];

module.exports = {
  navbarItems,
  avatarIons,
};
